language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm test
notifications:
  slack:
    on_success: never
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
