language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
install:
  - npm install
  - npm prune
script:
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
